#!/usr/bin/env ruby

require 'fileutils'

home = Dir.home
folderPath = "/Library/Developer/Xcode/Templates/File\ Templates/Custom\ Templates/VIPER.xctemplate/"

FileUtils.mkdir_p(home + folderPath) unless File.exists?(home + folderPath)

FileUtils.cp_r 'VIPER.xctemplate/.', (home + folderPath)
